create schema banco;

create table banco.persona
(
    personaid      integer generated by default as identity
        primary key,
    nombre         varchar(100) not null,
    genero         varchar(50)  not null,
    edad           numeric(3)   not null,
    identificacion varchar(20)  not null,
    direccion      varchar(100) not null,
    telefono       varchar(20)  not null
);

comment on table banco.persona is 'tabla donde se almacenan a las personas';

alter table banco.persona
    owner to postgres;

create table banco.cliente
(
    personaid  integer      not null
        primary key
        references banco.persona,
    contrasena varchar(100) not null,
    estado     boolean      not null
);

comment on table banco.cliente is 'tabla donde se almacenan los clientes';

alter table banco.cliente
    owner to postgres;

create table banco.cuenta
(
    cuentaid     integer generated by default as identity
        constraint cuenta_pk
            primary key,
    numerocuenta varchar(20)      not null,
    tipocuenta   varchar(20)      not null,
    saldoinicial double precision not null,
    estado       boolean          not null,
    clienteid    integer          not null
        constraint cuenta_cliente_personaid_fk
            references banco.cliente
);

comment on table banco.cuenta is 'tabla donde se almacena las cuentas de los usuarios';

alter table banco.cuenta
    owner to postgres;

create table banco.movimiento
(
    movimientoid   integer generated by default as identity
        constraint movimiento_pk
            primary key,
    fecha          date             not null,
    tipomovimiento varchar(20)      not null,
    valor          double precision not null,
    saldo          double precision not null,
    cuentaid       integer          not null
        constraint movimiento_cuenta_cuentaid_fk
            references banco.cuenta
);

alter table banco.movimiento
    owner to postgres;

